resources:
  repositories:
  - repository: SkypeSpaces-Infra
    type: git
    name: SkypeSpaces-Infra

name: $(date:yyyyMMdd)$(rev:rr)
jobs:
- template: azure-devops-templates/steps/coral-steps.yml@SkypeSpaces-Infra