resources:
  repositories:
  - repository: SkypeSpaces-Infra
    type: git
    name: SkypeSpaces-Infra

name: $(date:yyyyMMdd)$(rev:rr)
jobs:
# Do not remove this step. This is how we enforce an audit trail for CredScan runs in CI build definitions.
- template: azure-devops-templates/steps/coral-steps.yml@SkypeSpaces-Infra